services:
    postgres:
        image: postgres:15
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - /volume2/docker/configs/cf.events/data:/var/lib/postgresql/data
        restart: unless-stopped

    cf-events-web:
        image: ghcr.io/pjominet/cf.events-web:latest
        container_name: events-web
        mem_limit: 1g
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
        volumes:
            - /volume2/docker/configs/cf.events/keys:/app/keys:rw
            - /volume2/docker/configs/cf.events/logs:/app/logs:rw
        ports:
            - 5019:8082
        depends_on:
            - postgres
        networks:
            - proxy-net
        restart: unless-stopped

networks:
    proxy-net:
        external: true
