<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.8" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.0-preview.1.25120.3" />
        <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\CF.Events.Shared\CF.Events.Shared.csproj" />
    </ItemGroup>
    <ItemGroup>
      <_ContentIncludedByDefault Remove="wwwroot\invitations\engagement\assets\invitation.jpeg" />
      <_ContentIncludedByDefault Remove="wwwroot\invitations\engagement\assets\location.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\invitations\engagement\index.html" />
      <_ContentIncludedByDefault Remove="wwwroot\invitations\sample\index.html" />
    </ItemGroup>

</Project>
